### ISSUE TITLE
cant find `docfx.json` when running example

### ISSUE THREAD

**Issue by AaronLayton** [StewMcc/docker-docfx#1]
I am trying to run

docker run --rm -it stewmcc/docker-docfx:latest docfx build inside my project folder that contains a docfx.json file but I get the following errors

λ docker run -it stewmcc/docker-docfx:latest docfx build
[19-03-07 04:19:12.784]Error:Either provide config file or specify content files to start building documentation.
am I right in thinking I need to copy my files into the docker image? or should it have access to my local file system to read the files it needs?

**Comment by evan-schiewe** [comment]
@AaronLayton Docker containers do not have access to your local filesystem.  You could copy the files into the container after starting it, but you're better off using a mount.

https://docs.docker.com/storage/bind-mounts/
