### ISSUE TITLE
Add a version with the tag "latest"

### ISSUE THREAD

**Issue by iBrotNano** [StewMcc/docker-docfx#3]
Hi,

maybe it is a good feature to have a file to build the latest version. For example to publish an image with the tag "latest".

I figured out that the uri https://github.com/dotnet/docfx/releases/latest/download/docfx.zip points to the latest release of docfx.zip.

This will always create an image with the latest version of docfx:

```yml
&& wget -q -P /tmp https://github.com/dotnet/docfx/releases/latest/download/docfx.zip \
    && mkdir -p /opt/docfx \
    && unzip /tmp/docfx.zip -d /opt/docfx \
    && echo '#!/bin/bash\nmono /opt/docfx/docfx.exe $@' > /usr/bin/docfx \
    && chmod +x /usr/bin/docfx \
    && rm -r -f /tmp/*
```

**Comment by StewMcc** [comment]
Latest tag will now give you this ^^ instead (don't really use this myself much). If want merge request with stable combo of mono and docfx will merge.
